### ISSUE TITLE
Cache Corruption

### ISSUE THREAD

**Issue by RnbWd** [maxogden/electron-download#1]
Continuation from : https://github.com/mafintosh/electron-prebuilt/issues/25

The problem is assuming the download completes, here: 

```
20   if (pathExists.sync(cachedZip)) {
21      return cb(null, cachedZip)
22    } 
```

If the download doesn't complete, then the cache is corrupted. the solution suggested by @mafintosh was creating a tmp directory initially, but this is the repo to make that PR now

**Comment by RnbWd** [comment]
This is the error message for reference: 

```
> electron-prebuilt@0.25.3-2 install /Users/rnbwd/Projects/forks/electron-prebuilt
> node install.js

/Users/rnbwd/Projects/forks/electron-prebuilt/install.js:15
  throw err
        ^
Error: end of central directory record signature not found
    at /Users/rnbwd/Projects/forks/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/index.js:98:14
    at /Users/rnbwd/Projects/forks/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/index.js:342:5
    at /Users/rnbwd/Projects/forks/electron-prebuilt/node_modules/extract-zip/node_modules/yauzl/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:527:17)
```

**Comment by RnbWd** [comment]
```
$ ls  ~/.electron
electron-v0.25.3-darwin-x64.zip
```

It's an incomplete download, I'm not sure if OP that started the other issue realized what was happening

**Comment by mafintosh** [comment]
@RnbWd yes we should just impl the tmp file strategy here

**Comment by maxogden** [comment]
oh yea this is an easy fix
